### ISSUE TITLE
 Event is not triggered when address fields are set while creating Lead

### ISSUE THREAD

**Issue by matuagarwal** [kevinohara80/nforce#144] opened 2018-01-01 09:14 UTC
If a create a Lead object in Salesforce and along with mandatory properties if i set address properties like  street, city, state, zip, country, nforce is unable to detect events

I tried with 1.9.0 version of nforce

Is this a known issue or limitation ?

**Comment by kevinohara80** [comment] 2018-01-23 13:01
Can you provide a code example?

**Comment by srihakum** [comment] 2018-01-31 14:00
@kevinohara80 With Salesforce connection version 34 we see this issue, however updating to 37 or later events are generated even when address fields are populated. But with latest API versions we see that events stops working after some time. Looks like there some issue is already reported https://github.com/kevinohara80/nforce/issues/131. Hoping to see that fixed, and this can marked as resolved.

**Comment by kevinohara80** [comment] 2018-01-31 19:03
@srihakum My suggestion in the other thread was to try upgrading Faye. If you or someone else is willing to try this and test it out, I'd be happy to merge it if it fixes the issue. I don't have the time at the moment to really test this.

**Comment by kevinohara80** [comment] 2018-11-01 22:12
Closed. Dupe of #131 and because of inactivity.

**Closed by kevinohara80** 2018-11-01 22:12 UTC
